name: API Syntax Check

on: [push,pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' 
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal
      
    - name: Install report generator
      run: dotnet tool install --global donet-repostgeneration-globaltool

    - name: Run Code Style Analysis (Optional)
      run: donet build /p:RunCodeAnalysis=true

